{
 "title": "Fogbow ATM Prod",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "RAS",
   "type": "singlestat",
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "ras_reachability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "AS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "as_reachability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "FNS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "fns_reachability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "MS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ms_reachability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "Compute Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "compute_availability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "Compute Sucess Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "compute_success_rate{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Compute Sucess Rate"
    }
   ]
  },
  {
   "title": "Compute Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "compute_latency{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Compute Sucess Rate"
    }
   ]
  },
  {
   "title": "Volume Availability",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "volume_availability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "Volume Sucess Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "volume_success_rate{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Volume Sucess Rate"
    }
   ]
  },
  {
   "title": "Volume Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "volume_latency{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Volume Sucess Rate"
    }
   ]
  },
  {
   "title": "Network Availability",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "network_availability{target_label=\"atm-prod\"}"
    }
   ]
  },
  {
   "title": "Network Sucess Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "network_success_rate{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Network Sucess Rate"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "network_latency{service=\"ras\", target_label=\"atm-prod\"}",
     "legendFormat": "Network Sucess Rate"
    }
   ]
  }
 ]
}